### ISSUE TITLE
Caused by: java.lang.RuntimeException: failed to resolve Scalafmt version '3.0.0'

### ISSUE THREAD

**Issue by shivamka1** [AvaPL/scalafmt-native-formatter#15]
When this github action is run for configuration defined below, it fails as shown below:

.scalafmt.conf
```
version = 3.0.0
```

Exception
```
org.scalafmt.cli.FailedToFormat: /github/workspace/.scalafmt.conf
Caused by: java.lang.RuntimeException: failed to resolve Scalafmt version '3.0.0'
	at org.scalafmt.interfaces.ScalafmtReporter.error(ScalafmtReporter.java:38)
	at org.scalafmt.cli.ScalafmtCliReporter.error(ScalafmtCliReporter.scala:15)
	at org.scalafmt.dynamic.ScalafmtDynamic.reportError(ScalafmtDynamic.scala:91)
	at org.scalafmt.dynamic.ScalafmtDynamic.format(ScalafmtDynamic.scala:74)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.handleFile(ScalafmtDynamicRunner.scala:96)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$4(ScalafmtDynamicRunner.scala:55)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$4$adapted(ScalafmtDynamicRunner.scala:49)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.$anonfun$run$3(ScalafmtDynamicRunner.scala:49)
	at scala.util.control.Breaks.breakable(Breaks.scala:42)
	at org.scalafmt.cli.ScalafmtDynamicRunner$.run(ScalafmtDynamicRunner.scala:49)
	at org.scalafmt.cli.Cli$.runWithRunner(Cli.scala:135)
	at org.scalafmt.cli.Cli$.run(Cli.scala:84)
	at org.scalafmt.cli.Cli$.mainWithOptions(Cli.scala:69)
	at org.scalafmt.cli.Cli$.main(Cli.scala:58)
	at org.scalafmt.cli.Cli.main(Cli.scala)
```

**Comment by AvaPL** [comment]
Hi, thank you for using this action. Are you sure that you've reported the issue on correct repository? I've checked your latest pipelines and it seems that this action worked fine - https://github.com/iamsmkr/greeter/runs/3381218127. The one that did not work and thrown that exception was [openlawteam/scalafmt-ci@v2](https://github.com/openlawteam/scalafmt-ci) - https://github.com/iamsmkr/greeter/runs/3381166401.

**Comment by AvaPL** [comment]
I'm closing the issue due to no response. If you have any other problems, please open another issue.
